#!/usr/bin/env python3
"""Extract HTML from web_ui.h, gzip compress it, write as C byte array to web_ui_gz.h"""
import gzip, re, os

src = os.path.join(os.path.dirname(__file__), 'src', 'web_ui.h')
dst = os.path.join(os.path.dirname(__file__), 'src', 'web_ui_gz.h')

# Read web_ui.h and extract the raw literal content
with open(src, 'r', encoding='utf-8') as f:
    content = f.read()

# Extract HTML between R"rawliteral( and )rawliteral"
m = re.search(r'R"rawliteral\((.*?)\)rawliteral"', content, re.DOTALL)
if not m:
    print("ERROR: Could not find rawliteral in web_ui.h")
    exit(1)

html = m.group(1).encode('utf-8')
print(f"HTML size: {len(html)} bytes")

# Gzip compress
gz = gzip.compress(html, compresslevel=9)
print(f"Gzip size: {len(gz)} bytes ({100*len(gz)//len(html)}%)")

# Write C header
with open(dst, 'w') as f:
    f.write('#pragma once\n\n')
    f.write(f'// Auto-generated by compress_ui.py — do not edit\n')
    f.write(f'// Original: {len(html)} bytes, Compressed: {len(gz)} bytes\n\n')
    f.write(f'const size_t WEB_UI_GZ_LEN = {len(gz)};\n')
    f.write(f'const uint8_t WEB_UI_GZ[] PROGMEM = {{\n')
    for i in range(0, len(gz), 16):
        chunk = gz[i:i+16]
        f.write('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
    f.write('};\n')

print(f"Written to {dst}")
