[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    me-no-dev/ESPAsyncWebServer@^1.2.4
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@^7.3.0
    https://github.com/aed3/PS4-esp32.git
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_LOOP_STACK_SIZE=4096
